using System.Collections;
using System.Collections.Generic;
using DesignPattern;
using UnityEngine;

public class PoolTest : MonoBehaviour
{
    [SerializeField] private PooledObjectTest _prefab;
    private ObjectPool _pool;
    private PooledObject _temp;

    private void Awake()
    {
        _pool = new ObjectPool(_prefab, 10);
    }

    private void Update()
    {
        if (Input.GetKeyDown(KeyCode.Alpha1))
        {
            _temp = _pool.PopPool();
            _temp.transform.parent = transform;
        }
        if (Input.GetKeyDown(KeyCode.Alpha2))
        {
            _temp.ReturnPool();
            // 혹은 _pool.PushPool(_temp);
        }
    } 


}
